/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wanghong_grpc_usersystem_UserSystemNative */

#ifndef _Included_com_wanghong_grpc_usersystem_UserSystemNative
#define _Included_com_wanghong_grpc_usersystem_UserSystemNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wanghong_grpc_usersystem_UserSystemNative
 * Method:    naInit
 * Signature: (Ljava/lang/String;ILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_wanghong_grpc_usersystem_UserSystemNative_naInit
  (JNIEnv *, jobject, jstring, jint, jstring);

/*
 * Class:     com_wanghong_grpc_usersystem_UserSystemNative
 * Method:    naRegister
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wanghong_grpc_usersystem_UserSystemNative_naRegister
  (JNIEnv *, jobject, jstring, jstring, jstring, jint);

/*
 * Class:     com_wanghong_grpc_usersystem_UserSystemNative
 * Method:    naLogin
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wanghong_grpc_usersystem_UserSystemNative_naLogin
  (JNIEnv *, jobject, jstring, jstring, jstring, jint);

/*
 * Class:     com_wanghong_grpc_usersystem_UserSystemNative
 * Method:    naCheckLogin
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wanghong_grpc_usersystem_UserSystemNative_naCheckLogin
  (JNIEnv *, jobject, jstring, jstring, jstring, jint);

/*
 * Class:     com_wanghong_grpc_usersystem_UserSystemNative
 * Method:    naLogout
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wanghong_grpc_usersystem_UserSystemNative_naLogout
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_wanghong_grpc_usersystem_UserSystemNative_Companion */

#ifndef _Included_com_wanghong_grpc_usersystem_UserSystemNative_Companion
#define _Included_com_wanghong_grpc_usersystem_UserSystemNative_Companion
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
