// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usersystem.proto

package com.wanghong.grpc.usersystem.proto;

public interface CheckLoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:usersystem.CheckLoginResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>required .usersystem.CommonResponse response = 1;</code>
   */
  boolean hasResponse();
  /**
   * <code>required .usersystem.CommonResponse response = 1;</code>
   */
  com.wanghong.grpc.usersystem.proto.CommonResponse getResponse();
}
