// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usersystem.proto

package com.wanghong.grpc.usersystem.proto;

public interface CheckLoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:usersystem.CheckLoginRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>required string username = 1;</code>
   */
  boolean hasUsername();
  /**
   * <code>required string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>required string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>required string token = 2;</code>
   */
  boolean hasToken();
  /**
   * <code>required string token = 2;</code>
   */
  java.lang.String getToken();
  /**
   * <code>required string token = 2;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>required string device_id = 3;</code>
   */
  boolean hasDeviceId();
  /**
   * <code>required string device_id = 3;</code>
   */
  java.lang.String getDeviceId();
  /**
   * <code>required string device_id = 3;</code>
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <code>required .usersystem.Platform from_platform = 4;</code>
   */
  boolean hasFromPlatform();
  /**
   * <code>required .usersystem.Platform from_platform = 4;</code>
   */
  com.wanghong.grpc.usersystem.proto.Platform getFromPlatform();

  /**
   * <code>optional .usersystem.Geo geo = 5;</code>
   */
  boolean hasGeo();
  /**
   * <code>optional .usersystem.Geo geo = 5;</code>
   */
  com.wanghong.grpc.usersystem.proto.Geo getGeo();
}
