// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usersystem.proto

package com.wanghong.grpc.usersystem.proto;

/**
 * Protobuf type {@code usersystem.CommonResponse}
 */
public  final class CommonResponse extends
    com.google.protobuf.GeneratedMessageLite<
        CommonResponse, CommonResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:usersystem.CommonResponse)
    CommonResponseOrBuilder {
  private CommonResponse() {
    message_ = "";
    grpcErrorMessage_ = "";
    grpcErrorDetails_ = "";
  }
  private int bitField0_;
  public static final int CODE_FIELD_NUMBER = 1;
  private int code_;
  /**
   * <code>required .usersystem.ResponseCode code = 1;</code>
   */
  @java.lang.Override
  public boolean hasCode() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required .usersystem.ResponseCode code = 1;</code>
   */
  @java.lang.Override
  public com.wanghong.grpc.usersystem.proto.ResponseCode getCode() {
    com.wanghong.grpc.usersystem.proto.ResponseCode result = com.wanghong.grpc.usersystem.proto.ResponseCode.forNumber(code_);
    return result == null ? com.wanghong.grpc.usersystem.proto.ResponseCode.OK : result;
  }
  /**
   * <code>required .usersystem.ResponseCode code = 1;</code>
   */
  private void setCode(com.wanghong.grpc.usersystem.proto.ResponseCode value) {
    if (value == null) {
      throw new NullPointerException();
    }
    bitField0_ |= 0x00000001;
    code_ = value.getNumber();
  }
  /**
   * <code>required .usersystem.ResponseCode code = 1;</code>
   */
  private void clearCode() {
    bitField0_ = (bitField0_ & ~0x00000001);
    code_ = 0;
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  private java.lang.String message_;
  /**
   * <code>optional string message = 2;</code>
   */
  @java.lang.Override
  public boolean hasMessage() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string message = 2;</code>
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    return message_;
  }
  /**
   * <code>optional string message = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(message_);
  }
  /**
   * <code>optional string message = 2;</code>
   */
  private void setMessage(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
    message_ = value;
  }
  /**
   * <code>optional string message = 2;</code>
   */
  private void clearMessage() {
    bitField0_ = (bitField0_ & ~0x00000002);
    message_ = getDefaultInstance().getMessage();
  }
  /**
   * <code>optional string message = 2;</code>
   */
  private void setMessageBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
    message_ = value.toStringUtf8();
  }

  public static final int GRPC_ERROR_CODE_FIELD_NUMBER = 3;
  private int grpcErrorCode_;
  /**
   * <code>optional int32 grpc_error_code = 3;</code>
   */
  @java.lang.Override
  public boolean hasGrpcErrorCode() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional int32 grpc_error_code = 3;</code>
   */
  @java.lang.Override
  public int getGrpcErrorCode() {
    return grpcErrorCode_;
  }
  /**
   * <code>optional int32 grpc_error_code = 3;</code>
   */
  private void setGrpcErrorCode(int value) {
    bitField0_ |= 0x00000004;
    grpcErrorCode_ = value;
  }
  /**
   * <code>optional int32 grpc_error_code = 3;</code>
   */
  private void clearGrpcErrorCode() {
    bitField0_ = (bitField0_ & ~0x00000004);
    grpcErrorCode_ = 0;
  }

  public static final int GRPC_ERROR_MESSAGE_FIELD_NUMBER = 4;
  private java.lang.String grpcErrorMessage_;
  /**
   * <code>optional string grpc_error_message = 4;</code>
   */
  @java.lang.Override
  public boolean hasGrpcErrorMessage() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional string grpc_error_message = 4;</code>
   */
  @java.lang.Override
  public java.lang.String getGrpcErrorMessage() {
    return grpcErrorMessage_;
  }
  /**
   * <code>optional string grpc_error_message = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGrpcErrorMessageBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(grpcErrorMessage_);
  }
  /**
   * <code>optional string grpc_error_message = 4;</code>
   */
  private void setGrpcErrorMessage(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
    grpcErrorMessage_ = value;
  }
  /**
   * <code>optional string grpc_error_message = 4;</code>
   */
  private void clearGrpcErrorMessage() {
    bitField0_ = (bitField0_ & ~0x00000008);
    grpcErrorMessage_ = getDefaultInstance().getGrpcErrorMessage();
  }
  /**
   * <code>optional string grpc_error_message = 4;</code>
   */
  private void setGrpcErrorMessageBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
    grpcErrorMessage_ = value.toStringUtf8();
  }

  public static final int GRPC_ERROR_DETAILS_FIELD_NUMBER = 5;
  private java.lang.String grpcErrorDetails_;
  /**
   * <code>optional string grpc_error_details = 5;</code>
   */
  @java.lang.Override
  public boolean hasGrpcErrorDetails() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional string grpc_error_details = 5;</code>
   */
  @java.lang.Override
  public java.lang.String getGrpcErrorDetails() {
    return grpcErrorDetails_;
  }
  /**
   * <code>optional string grpc_error_details = 5;</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGrpcErrorDetailsBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(grpcErrorDetails_);
  }
  /**
   * <code>optional string grpc_error_details = 5;</code>
   */
  private void setGrpcErrorDetails(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
    grpcErrorDetails_ = value;
  }
  /**
   * <code>optional string grpc_error_details = 5;</code>
   */
  private void clearGrpcErrorDetails() {
    bitField0_ = (bitField0_ & ~0x00000010);
    grpcErrorDetails_ = getDefaultInstance().getGrpcErrorDetails();
  }
  /**
   * <code>optional string grpc_error_details = 5;</code>
   */
  private void setGrpcErrorDetailsBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
    grpcErrorDetails_ = value.toStringUtf8();
  }

  public static com.wanghong.grpc.usersystem.proto.CommonResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.wanghong.grpc.usersystem.proto.CommonResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.wanghong.grpc.usersystem.proto.CommonResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.wanghong.grpc.usersystem.proto.CommonResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.wanghong.grpc.usersystem.proto.CommonResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.wanghong.grpc.usersystem.proto.CommonResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.wanghong.grpc.usersystem.proto.CommonResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.wanghong.grpc.usersystem.proto.CommonResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.wanghong.grpc.usersystem.proto.CommonResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.wanghong.grpc.usersystem.proto.CommonResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.wanghong.grpc.usersystem.proto.CommonResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.wanghong.grpc.usersystem.proto.CommonResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.wanghong.grpc.usersystem.proto.CommonResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code usersystem.CommonResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.wanghong.grpc.usersystem.proto.CommonResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:usersystem.CommonResponse)
      com.wanghong.grpc.usersystem.proto.CommonResponseOrBuilder {
    // Construct using com.wanghong.grpc.usersystem.proto.CommonResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>required .usersystem.ResponseCode code = 1;</code>
     */
    @java.lang.Override
    public boolean hasCode() {
      return instance.hasCode();
    }
    /**
     * <code>required .usersystem.ResponseCode code = 1;</code>
     */
    @java.lang.Override
    public com.wanghong.grpc.usersystem.proto.ResponseCode getCode() {
      return instance.getCode();
    }
    /**
     * <code>required .usersystem.ResponseCode code = 1;</code>
     */
    public Builder setCode(com.wanghong.grpc.usersystem.proto.ResponseCode value) {
      copyOnWrite();
      instance.setCode(value);
      return this;
    }
    /**
     * <code>required .usersystem.ResponseCode code = 1;</code>
     */
    public Builder clearCode() {
      copyOnWrite();
      instance.clearCode();
      return this;
    }

    /**
     * <code>optional string message = 2;</code>
     */
    @java.lang.Override
    public boolean hasMessage() {
      return instance.hasMessage();
    }
    /**
     * <code>optional string message = 2;</code>
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      return instance.getMessage();
    }
    /**
     * <code>optional string message = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      return instance.getMessageBytes();
    }
    /**
     * <code>optional string message = 2;</code>
     */
    public Builder setMessage(
        java.lang.String value) {
      copyOnWrite();
      instance.setMessage(value);
      return this;
    }
    /**
     * <code>optional string message = 2;</code>
     */
    public Builder clearMessage() {
      copyOnWrite();
      instance.clearMessage();
      return this;
    }
    /**
     * <code>optional string message = 2;</code>
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMessageBytes(value);
      return this;
    }

    /**
     * <code>optional int32 grpc_error_code = 3;</code>
     */
    @java.lang.Override
    public boolean hasGrpcErrorCode() {
      return instance.hasGrpcErrorCode();
    }
    /**
     * <code>optional int32 grpc_error_code = 3;</code>
     */
    @java.lang.Override
    public int getGrpcErrorCode() {
      return instance.getGrpcErrorCode();
    }
    /**
     * <code>optional int32 grpc_error_code = 3;</code>
     */
    public Builder setGrpcErrorCode(int value) {
      copyOnWrite();
      instance.setGrpcErrorCode(value);
      return this;
    }
    /**
     * <code>optional int32 grpc_error_code = 3;</code>
     */
    public Builder clearGrpcErrorCode() {
      copyOnWrite();
      instance.clearGrpcErrorCode();
      return this;
    }

    /**
     * <code>optional string grpc_error_message = 4;</code>
     */
    @java.lang.Override
    public boolean hasGrpcErrorMessage() {
      return instance.hasGrpcErrorMessage();
    }
    /**
     * <code>optional string grpc_error_message = 4;</code>
     */
    @java.lang.Override
    public java.lang.String getGrpcErrorMessage() {
      return instance.getGrpcErrorMessage();
    }
    /**
     * <code>optional string grpc_error_message = 4;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGrpcErrorMessageBytes() {
      return instance.getGrpcErrorMessageBytes();
    }
    /**
     * <code>optional string grpc_error_message = 4;</code>
     */
    public Builder setGrpcErrorMessage(
        java.lang.String value) {
      copyOnWrite();
      instance.setGrpcErrorMessage(value);
      return this;
    }
    /**
     * <code>optional string grpc_error_message = 4;</code>
     */
    public Builder clearGrpcErrorMessage() {
      copyOnWrite();
      instance.clearGrpcErrorMessage();
      return this;
    }
    /**
     * <code>optional string grpc_error_message = 4;</code>
     */
    public Builder setGrpcErrorMessageBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setGrpcErrorMessageBytes(value);
      return this;
    }

    /**
     * <code>optional string grpc_error_details = 5;</code>
     */
    @java.lang.Override
    public boolean hasGrpcErrorDetails() {
      return instance.hasGrpcErrorDetails();
    }
    /**
     * <code>optional string grpc_error_details = 5;</code>
     */
    @java.lang.Override
    public java.lang.String getGrpcErrorDetails() {
      return instance.getGrpcErrorDetails();
    }
    /**
     * <code>optional string grpc_error_details = 5;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGrpcErrorDetailsBytes() {
      return instance.getGrpcErrorDetailsBytes();
    }
    /**
     * <code>optional string grpc_error_details = 5;</code>
     */
    public Builder setGrpcErrorDetails(
        java.lang.String value) {
      copyOnWrite();
      instance.setGrpcErrorDetails(value);
      return this;
    }
    /**
     * <code>optional string grpc_error_details = 5;</code>
     */
    public Builder clearGrpcErrorDetails() {
      copyOnWrite();
      instance.clearGrpcErrorDetails();
      return this;
    }
    /**
     * <code>optional string grpc_error_details = 5;</code>
     */
    public Builder setGrpcErrorDetailsBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setGrpcErrorDetailsBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:usersystem.CommonResponse)
  }
  private byte memoizedIsInitialized = 2;
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.wanghong.grpc.usersystem.proto.CommonResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "code_",
            com.wanghong.grpc.usersystem.proto.ResponseCode.internalGetVerifier(),
            "message_",
            "grpcErrorCode_",
            "grpcErrorMessage_",
            "grpcErrorDetails_",
          };
          java.lang.String info =
              "\u0001\u0005\u0000\u0001\u0001\u0005\u0005\u0000\u0000\u0001\u0001\u050c\u0000\u0002" +
              "\b\u0001\u0003\u0004\u0002\u0004\b\u0003\u0005\b\u0004";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.wanghong.grpc.usersystem.proto.CommonResponse> parser = PARSER;
        if (parser == null) {
          synchronized (com.wanghong.grpc.usersystem.proto.CommonResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return memoizedIsInitialized;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:usersystem.CommonResponse)
  private static final com.wanghong.grpc.usersystem.proto.CommonResponse DEFAULT_INSTANCE;
  static {
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = new CommonResponse();
  }

  static {
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      CommonResponse.class, DEFAULT_INSTANCE);
  }
  public static com.wanghong.grpc.usersystem.proto.CommonResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<CommonResponse> PARSER;

  public static com.google.protobuf.Parser<CommonResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

