// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usersystem.proto

package com.wanghong.grpc.usersystem.proto;

public interface CommonResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:usersystem.CommonResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>required .usersystem.ResponseCode code = 1;</code>
   */
  boolean hasCode();
  /**
   * <code>required .usersystem.ResponseCode code = 1;</code>
   */
  com.wanghong.grpc.usersystem.proto.ResponseCode getCode();

  /**
   * <code>optional string message = 2;</code>
   */
  boolean hasMessage();
  /**
   * <code>optional string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>optional int32 grpc_error_code = 3;</code>
   */
  boolean hasGrpcErrorCode();
  /**
   * <code>optional int32 grpc_error_code = 3;</code>
   */
  int getGrpcErrorCode();

  /**
   * <code>optional string grpc_error_message = 4;</code>
   */
  boolean hasGrpcErrorMessage();
  /**
   * <code>optional string grpc_error_message = 4;</code>
   */
  java.lang.String getGrpcErrorMessage();
  /**
   * <code>optional string grpc_error_message = 4;</code>
   */
  com.google.protobuf.ByteString
      getGrpcErrorMessageBytes();

  /**
   * <code>optional string grpc_error_details = 5;</code>
   */
  boolean hasGrpcErrorDetails();
  /**
   * <code>optional string grpc_error_details = 5;</code>
   */
  java.lang.String getGrpcErrorDetails();
  /**
   * <code>optional string grpc_error_details = 5;</code>
   */
  com.google.protobuf.ByteString
      getGrpcErrorDetailsBytes();
}
