// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usersystem.proto

package com.wanghong.grpc.usersystem.proto;

/**
 * Protobuf type {@code usersystem.Geo}
 */
public  final class Geo extends
    com.google.protobuf.GeneratedMessageLite<
        Geo, Geo.Builder> implements
    // @@protoc_insertion_point(message_implements:usersystem.Geo)
    GeoOrBuilder {
  private Geo() {
  }
  private int bitField0_;
  public static final int LAT_FIELD_NUMBER = 1;
  private double lat_;
  /**
   * <code>required double lat = 1;</code>
   */
  @java.lang.Override
  public boolean hasLat() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required double lat = 1;</code>
   */
  @java.lang.Override
  public double getLat() {
    return lat_;
  }
  /**
   * <code>required double lat = 1;</code>
   */
  private void setLat(double value) {
    bitField0_ |= 0x00000001;
    lat_ = value;
  }
  /**
   * <code>required double lat = 1;</code>
   */
  private void clearLat() {
    bitField0_ = (bitField0_ & ~0x00000001);
    lat_ = 0D;
  }

  public static final int LNG_FIELD_NUMBER = 2;
  private double lng_;
  /**
   * <code>required double lng = 2;</code>
   */
  @java.lang.Override
  public boolean hasLng() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required double lng = 2;</code>
   */
  @java.lang.Override
  public double getLng() {
    return lng_;
  }
  /**
   * <code>required double lng = 2;</code>
   */
  private void setLng(double value) {
    bitField0_ |= 0x00000002;
    lng_ = value;
  }
  /**
   * <code>required double lng = 2;</code>
   */
  private void clearLng() {
    bitField0_ = (bitField0_ & ~0x00000002);
    lng_ = 0D;
  }

  public static com.wanghong.grpc.usersystem.proto.Geo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.wanghong.grpc.usersystem.proto.Geo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.wanghong.grpc.usersystem.proto.Geo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.wanghong.grpc.usersystem.proto.Geo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.wanghong.grpc.usersystem.proto.Geo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.wanghong.grpc.usersystem.proto.Geo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.wanghong.grpc.usersystem.proto.Geo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.wanghong.grpc.usersystem.proto.Geo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.wanghong.grpc.usersystem.proto.Geo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.wanghong.grpc.usersystem.proto.Geo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.wanghong.grpc.usersystem.proto.Geo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.wanghong.grpc.usersystem.proto.Geo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.wanghong.grpc.usersystem.proto.Geo prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code usersystem.Geo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.wanghong.grpc.usersystem.proto.Geo, Builder> implements
      // @@protoc_insertion_point(builder_implements:usersystem.Geo)
      com.wanghong.grpc.usersystem.proto.GeoOrBuilder {
    // Construct using com.wanghong.grpc.usersystem.proto.Geo.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>required double lat = 1;</code>
     */
    @java.lang.Override
    public boolean hasLat() {
      return instance.hasLat();
    }
    /**
     * <code>required double lat = 1;</code>
     */
    @java.lang.Override
    public double getLat() {
      return instance.getLat();
    }
    /**
     * <code>required double lat = 1;</code>
     */
    public Builder setLat(double value) {
      copyOnWrite();
      instance.setLat(value);
      return this;
    }
    /**
     * <code>required double lat = 1;</code>
     */
    public Builder clearLat() {
      copyOnWrite();
      instance.clearLat();
      return this;
    }

    /**
     * <code>required double lng = 2;</code>
     */
    @java.lang.Override
    public boolean hasLng() {
      return instance.hasLng();
    }
    /**
     * <code>required double lng = 2;</code>
     */
    @java.lang.Override
    public double getLng() {
      return instance.getLng();
    }
    /**
     * <code>required double lng = 2;</code>
     */
    public Builder setLng(double value) {
      copyOnWrite();
      instance.setLng(value);
      return this;
    }
    /**
     * <code>required double lng = 2;</code>
     */
    public Builder clearLng() {
      copyOnWrite();
      instance.clearLng();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:usersystem.Geo)
  }
  private byte memoizedIsInitialized = 2;
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.wanghong.grpc.usersystem.proto.Geo();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "lat_",
            "lng_",
          };
          java.lang.String info =
              "\u0001\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0002\u0001\u0500\u0000\u0002" +
              "\u0500\u0001";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.wanghong.grpc.usersystem.proto.Geo> parser = PARSER;
        if (parser == null) {
          synchronized (com.wanghong.grpc.usersystem.proto.Geo.class) {
            parser = PARSER;
            if (parser == null) {
              parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return memoizedIsInitialized;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:usersystem.Geo)
  private static final com.wanghong.grpc.usersystem.proto.Geo DEFAULT_INSTANCE;
  static {
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = new Geo();
  }

  static {
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Geo.class, DEFAULT_INSTANCE);
  }
  public static com.wanghong.grpc.usersystem.proto.Geo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Geo> PARSER;

  public static com.google.protobuf.Parser<Geo> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

