// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usersystem.proto

package com.wanghong.grpc.usersystem.proto;

public interface GeoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:usersystem.Geo)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>required double lat = 1;</code>
   */
  boolean hasLat();
  /**
   * <code>required double lat = 1;</code>
   */
  double getLat();

  /**
   * <code>required double lng = 2;</code>
   */
  boolean hasLng();
  /**
   * <code>required double lng = 2;</code>
   */
  double getLng();
}
