// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usersystem.proto

package com.wanghong.grpc.usersystem.proto;

public interface LoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:usersystem.LoginRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>required string username = 1;</code>
   */
  boolean hasUsername();
  /**
   * <code>required string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>required string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>required string password = 2;</code>
   */
  boolean hasPassword();
  /**
   * <code>required string password = 2;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>required string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>required string device_id = 3;</code>
   */
  boolean hasDeviceId();
  /**
   * <code>required string device_id = 3;</code>
   */
  java.lang.String getDeviceId();
  /**
   * <code>required string device_id = 3;</code>
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <code>required .usersystem.Platform platform = 4;</code>
   */
  boolean hasPlatform();
  /**
   * <code>required .usersystem.Platform platform = 4;</code>
   */
  com.wanghong.grpc.usersystem.proto.Platform getPlatform();

  /**
   * <code>optional .usersystem.Geo geo = 5;</code>
   */
  boolean hasGeo();
  /**
   * <code>optional .usersystem.Geo geo = 5;</code>
   */
  com.wanghong.grpc.usersystem.proto.Geo getGeo();
}
