// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usersystem.proto

package com.wanghong.grpc.usersystem.proto;

/**
 * Protobuf type {@code usersystem.LoginRequest}
 */
public  final class LoginRequest extends
    com.google.protobuf.GeneratedMessageLite<
        LoginRequest, LoginRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:usersystem.LoginRequest)
    LoginRequestOrBuilder {
  private LoginRequest() {
    username_ = "";
    password_ = "";
    deviceId_ = "";
  }
  private int bitField0_;
  public static final int USERNAME_FIELD_NUMBER = 1;
  private java.lang.String username_;
  /**
   * <code>required string username = 1;</code>
   */
  @java.lang.Override
  public boolean hasUsername() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required string username = 1;</code>
   */
  @java.lang.Override
  public java.lang.String getUsername() {
    return username_;
  }
  /**
   * <code>required string username = 1;</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(username_);
  }
  /**
   * <code>required string username = 1;</code>
   */
  private void setUsername(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
    username_ = value;
  }
  /**
   * <code>required string username = 1;</code>
   */
  private void clearUsername() {
    bitField0_ = (bitField0_ & ~0x00000001);
    username_ = getDefaultInstance().getUsername();
  }
  /**
   * <code>required string username = 1;</code>
   */
  private void setUsernameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
    username_ = value.toStringUtf8();
  }

  public static final int PASSWORD_FIELD_NUMBER = 2;
  private java.lang.String password_;
  /**
   * <code>required string password = 2;</code>
   */
  @java.lang.Override
  public boolean hasPassword() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required string password = 2;</code>
   */
  @java.lang.Override
  public java.lang.String getPassword() {
    return password_;
  }
  /**
   * <code>required string password = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPasswordBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(password_);
  }
  /**
   * <code>required string password = 2;</code>
   */
  private void setPassword(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
    password_ = value;
  }
  /**
   * <code>required string password = 2;</code>
   */
  private void clearPassword() {
    bitField0_ = (bitField0_ & ~0x00000002);
    password_ = getDefaultInstance().getPassword();
  }
  /**
   * <code>required string password = 2;</code>
   */
  private void setPasswordBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
    password_ = value.toStringUtf8();
  }

  public static final int DEVICE_ID_FIELD_NUMBER = 3;
  private java.lang.String deviceId_;
  /**
   * <code>required string device_id = 3;</code>
   */
  @java.lang.Override
  public boolean hasDeviceId() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>required string device_id = 3;</code>
   */
  @java.lang.Override
  public java.lang.String getDeviceId() {
    return deviceId_;
  }
  /**
   * <code>required string device_id = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeviceIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(deviceId_);
  }
  /**
   * <code>required string device_id = 3;</code>
   */
  private void setDeviceId(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
    deviceId_ = value;
  }
  /**
   * <code>required string device_id = 3;</code>
   */
  private void clearDeviceId() {
    bitField0_ = (bitField0_ & ~0x00000004);
    deviceId_ = getDefaultInstance().getDeviceId();
  }
  /**
   * <code>required string device_id = 3;</code>
   */
  private void setDeviceIdBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
    deviceId_ = value.toStringUtf8();
  }

  public static final int PLATFORM_FIELD_NUMBER = 4;
  private int platform_;
  /**
   * <code>required .usersystem.Platform platform = 4;</code>
   */
  @java.lang.Override
  public boolean hasPlatform() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>required .usersystem.Platform platform = 4;</code>
   */
  @java.lang.Override
  public com.wanghong.grpc.usersystem.proto.Platform getPlatform() {
    com.wanghong.grpc.usersystem.proto.Platform result = com.wanghong.grpc.usersystem.proto.Platform.forNumber(platform_);
    return result == null ? com.wanghong.grpc.usersystem.proto.Platform.Type_Desktop : result;
  }
  /**
   * <code>required .usersystem.Platform platform = 4;</code>
   */
  private void setPlatform(com.wanghong.grpc.usersystem.proto.Platform value) {
    if (value == null) {
      throw new NullPointerException();
    }
    bitField0_ |= 0x00000008;
    platform_ = value.getNumber();
  }
  /**
   * <code>required .usersystem.Platform platform = 4;</code>
   */
  private void clearPlatform() {
    bitField0_ = (bitField0_ & ~0x00000008);
    platform_ = 0;
  }

  public static final int GEO_FIELD_NUMBER = 5;
  private com.wanghong.grpc.usersystem.proto.Geo geo_;
  /**
   * <code>optional .usersystem.Geo geo = 5;</code>
   */
  @java.lang.Override
  public boolean hasGeo() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional .usersystem.Geo geo = 5;</code>
   */
  @java.lang.Override
  public com.wanghong.grpc.usersystem.proto.Geo getGeo() {
    return geo_ == null ? com.wanghong.grpc.usersystem.proto.Geo.getDefaultInstance() : geo_;
  }
  /**
   * <code>optional .usersystem.Geo geo = 5;</code>
   */
  private void setGeo(com.wanghong.grpc.usersystem.proto.Geo value) {
    if (value == null) {
      throw new NullPointerException();
    }
    geo_ = value;
    bitField0_ |= 0x00000010;
    }
  /**
   * <code>optional .usersystem.Geo geo = 5;</code>
   */
  private void setGeo(
      com.wanghong.grpc.usersystem.proto.Geo.Builder builderForValue) {
    geo_ = builderForValue.build();
    bitField0_ |= 0x00000010;
  }
  /**
   * <code>optional .usersystem.Geo geo = 5;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeGeo(com.wanghong.grpc.usersystem.proto.Geo value) {
    if (value == null) {
      throw new NullPointerException();
    }
    if (geo_ != null &&
        geo_ != com.wanghong.grpc.usersystem.proto.Geo.getDefaultInstance()) {
      geo_ =
        com.wanghong.grpc.usersystem.proto.Geo.newBuilder(geo_).mergeFrom(value).buildPartial();
    } else {
      geo_ = value;
    }
    bitField0_ |= 0x00000010;
  }
  /**
   * <code>optional .usersystem.Geo geo = 5;</code>
   */
  private void clearGeo() {  geo_ = null;
    bitField0_ = (bitField0_ & ~0x00000010);
  }

  public static com.wanghong.grpc.usersystem.proto.LoginRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.wanghong.grpc.usersystem.proto.LoginRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.wanghong.grpc.usersystem.proto.LoginRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.wanghong.grpc.usersystem.proto.LoginRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.wanghong.grpc.usersystem.proto.LoginRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.wanghong.grpc.usersystem.proto.LoginRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.wanghong.grpc.usersystem.proto.LoginRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.wanghong.grpc.usersystem.proto.LoginRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.wanghong.grpc.usersystem.proto.LoginRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.wanghong.grpc.usersystem.proto.LoginRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.wanghong.grpc.usersystem.proto.LoginRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.wanghong.grpc.usersystem.proto.LoginRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.wanghong.grpc.usersystem.proto.LoginRequest prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code usersystem.LoginRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.wanghong.grpc.usersystem.proto.LoginRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:usersystem.LoginRequest)
      com.wanghong.grpc.usersystem.proto.LoginRequestOrBuilder {
    // Construct using com.wanghong.grpc.usersystem.proto.LoginRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>required string username = 1;</code>
     */
    @java.lang.Override
    public boolean hasUsername() {
      return instance.hasUsername();
    }
    /**
     * <code>required string username = 1;</code>
     */
    @java.lang.Override
    public java.lang.String getUsername() {
      return instance.getUsername();
    }
    /**
     * <code>required string username = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      return instance.getUsernameBytes();
    }
    /**
     * <code>required string username = 1;</code>
     */
    public Builder setUsername(
        java.lang.String value) {
      copyOnWrite();
      instance.setUsername(value);
      return this;
    }
    /**
     * <code>required string username = 1;</code>
     */
    public Builder clearUsername() {
      copyOnWrite();
      instance.clearUsername();
      return this;
    }
    /**
     * <code>required string username = 1;</code>
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUsernameBytes(value);
      return this;
    }

    /**
     * <code>required string password = 2;</code>
     */
    @java.lang.Override
    public boolean hasPassword() {
      return instance.hasPassword();
    }
    /**
     * <code>required string password = 2;</code>
     */
    @java.lang.Override
    public java.lang.String getPassword() {
      return instance.getPassword();
    }
    /**
     * <code>required string password = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      return instance.getPasswordBytes();
    }
    /**
     * <code>required string password = 2;</code>
     */
    public Builder setPassword(
        java.lang.String value) {
      copyOnWrite();
      instance.setPassword(value);
      return this;
    }
    /**
     * <code>required string password = 2;</code>
     */
    public Builder clearPassword() {
      copyOnWrite();
      instance.clearPassword();
      return this;
    }
    /**
     * <code>required string password = 2;</code>
     */
    public Builder setPasswordBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPasswordBytes(value);
      return this;
    }

    /**
     * <code>required string device_id = 3;</code>
     */
    @java.lang.Override
    public boolean hasDeviceId() {
      return instance.hasDeviceId();
    }
    /**
     * <code>required string device_id = 3;</code>
     */
    @java.lang.Override
    public java.lang.String getDeviceId() {
      return instance.getDeviceId();
    }
    /**
     * <code>required string device_id = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      return instance.getDeviceIdBytes();
    }
    /**
     * <code>required string device_id = 3;</code>
     */
    public Builder setDeviceId(
        java.lang.String value) {
      copyOnWrite();
      instance.setDeviceId(value);
      return this;
    }
    /**
     * <code>required string device_id = 3;</code>
     */
    public Builder clearDeviceId() {
      copyOnWrite();
      instance.clearDeviceId();
      return this;
    }
    /**
     * <code>required string device_id = 3;</code>
     */
    public Builder setDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDeviceIdBytes(value);
      return this;
    }

    /**
     * <code>required .usersystem.Platform platform = 4;</code>
     */
    @java.lang.Override
    public boolean hasPlatform() {
      return instance.hasPlatform();
    }
    /**
     * <code>required .usersystem.Platform platform = 4;</code>
     */
    @java.lang.Override
    public com.wanghong.grpc.usersystem.proto.Platform getPlatform() {
      return instance.getPlatform();
    }
    /**
     * <code>required .usersystem.Platform platform = 4;</code>
     */
    public Builder setPlatform(com.wanghong.grpc.usersystem.proto.Platform value) {
      copyOnWrite();
      instance.setPlatform(value);
      return this;
    }
    /**
     * <code>required .usersystem.Platform platform = 4;</code>
     */
    public Builder clearPlatform() {
      copyOnWrite();
      instance.clearPlatform();
      return this;
    }

    /**
     * <code>optional .usersystem.Geo geo = 5;</code>
     */
    @java.lang.Override
    public boolean hasGeo() {
      return instance.hasGeo();
    }
    /**
     * <code>optional .usersystem.Geo geo = 5;</code>
     */
    @java.lang.Override
    public com.wanghong.grpc.usersystem.proto.Geo getGeo() {
      return instance.getGeo();
    }
    /**
     * <code>optional .usersystem.Geo geo = 5;</code>
     */
    public Builder setGeo(com.wanghong.grpc.usersystem.proto.Geo value) {
      copyOnWrite();
      instance.setGeo(value);
      return this;
      }
    /**
     * <code>optional .usersystem.Geo geo = 5;</code>
     */
    public Builder setGeo(
        com.wanghong.grpc.usersystem.proto.Geo.Builder builderForValue) {
      copyOnWrite();
      instance.setGeo(builderForValue);
      return this;
    }
    /**
     * <code>optional .usersystem.Geo geo = 5;</code>
     */
    public Builder mergeGeo(com.wanghong.grpc.usersystem.proto.Geo value) {
      copyOnWrite();
      instance.mergeGeo(value);
      return this;
    }
    /**
     * <code>optional .usersystem.Geo geo = 5;</code>
     */
    public Builder clearGeo() {  copyOnWrite();
      instance.clearGeo();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:usersystem.LoginRequest)
  }
  private byte memoizedIsInitialized = 2;
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.wanghong.grpc.usersystem.proto.LoginRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "username_",
            "password_",
            "deviceId_",
            "platform_",
            com.wanghong.grpc.usersystem.proto.Platform.internalGetVerifier(),
            "geo_",
          };
          java.lang.String info =
              "\u0001\u0005\u0000\u0001\u0001\u0005\u0005\u0000\u0000\u0005\u0001\u0508\u0000\u0002" +
              "\u0508\u0001\u0003\u0508\u0002\u0004\u050c\u0003\u0005\u0409\u0004";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.wanghong.grpc.usersystem.proto.LoginRequest> parser = PARSER;
        if (parser == null) {
          synchronized (com.wanghong.grpc.usersystem.proto.LoginRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return memoizedIsInitialized;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:usersystem.LoginRequest)
  private static final com.wanghong.grpc.usersystem.proto.LoginRequest DEFAULT_INSTANCE;
  static {
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = new LoginRequest();
  }

  static {
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      LoginRequest.class, DEFAULT_INSTANCE);
  }
  public static com.wanghong.grpc.usersystem.proto.LoginRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<LoginRequest> PARSER;

  public static com.google.protobuf.Parser<LoginRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

