// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usersystem.proto

package com.wanghong.grpc.usersystem.proto;

/**
 * Protobuf type {@code usersystem.LoginResponse}
 */
public  final class LoginResponse extends
    com.google.protobuf.GeneratedMessageLite<
        LoginResponse, LoginResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:usersystem.LoginResponse)
    LoginResponseOrBuilder {
  private LoginResponse() {
    token_ = "";
  }
  private int bitField0_;
  public static final int RESPONSE_FIELD_NUMBER = 1;
  private com.wanghong.grpc.usersystem.proto.CommonResponse response_;
  /**
   * <code>required .usersystem.CommonResponse response = 1;</code>
   */
  @java.lang.Override
  public boolean hasResponse() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required .usersystem.CommonResponse response = 1;</code>
   */
  @java.lang.Override
  public com.wanghong.grpc.usersystem.proto.CommonResponse getResponse() {
    return response_ == null ? com.wanghong.grpc.usersystem.proto.CommonResponse.getDefaultInstance() : response_;
  }
  /**
   * <code>required .usersystem.CommonResponse response = 1;</code>
   */
  private void setResponse(com.wanghong.grpc.usersystem.proto.CommonResponse value) {
    if (value == null) {
      throw new NullPointerException();
    }
    response_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>required .usersystem.CommonResponse response = 1;</code>
   */
  private void setResponse(
      com.wanghong.grpc.usersystem.proto.CommonResponse.Builder builderForValue) {
    response_ = builderForValue.build();
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>required .usersystem.CommonResponse response = 1;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeResponse(com.wanghong.grpc.usersystem.proto.CommonResponse value) {
    if (value == null) {
      throw new NullPointerException();
    }
    if (response_ != null &&
        response_ != com.wanghong.grpc.usersystem.proto.CommonResponse.getDefaultInstance()) {
      response_ =
        com.wanghong.grpc.usersystem.proto.CommonResponse.newBuilder(response_).mergeFrom(value).buildPartial();
    } else {
      response_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>required .usersystem.CommonResponse response = 1;</code>
   */
  private void clearResponse() {  response_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int USERMODEL_FIELD_NUMBER = 2;
  private com.wanghong.grpc.usersystem.proto.UserModel userModel_;
  /**
   * <code>optional .usersystem.UserModel userModel = 2;</code>
   */
  @java.lang.Override
  public boolean hasUserModel() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .usersystem.UserModel userModel = 2;</code>
   */
  @java.lang.Override
  public com.wanghong.grpc.usersystem.proto.UserModel getUserModel() {
    return userModel_ == null ? com.wanghong.grpc.usersystem.proto.UserModel.getDefaultInstance() : userModel_;
  }
  /**
   * <code>optional .usersystem.UserModel userModel = 2;</code>
   */
  private void setUserModel(com.wanghong.grpc.usersystem.proto.UserModel value) {
    if (value == null) {
      throw new NullPointerException();
    }
    userModel_ = value;
    bitField0_ |= 0x00000002;
    }
  /**
   * <code>optional .usersystem.UserModel userModel = 2;</code>
   */
  private void setUserModel(
      com.wanghong.grpc.usersystem.proto.UserModel.Builder builderForValue) {
    userModel_ = builderForValue.build();
    bitField0_ |= 0x00000002;
  }
  /**
   * <code>optional .usersystem.UserModel userModel = 2;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeUserModel(com.wanghong.grpc.usersystem.proto.UserModel value) {
    if (value == null) {
      throw new NullPointerException();
    }
    if (userModel_ != null &&
        userModel_ != com.wanghong.grpc.usersystem.proto.UserModel.getDefaultInstance()) {
      userModel_ =
        com.wanghong.grpc.usersystem.proto.UserModel.newBuilder(userModel_).mergeFrom(value).buildPartial();
    } else {
      userModel_ = value;
    }
    bitField0_ |= 0x00000002;
  }
  /**
   * <code>optional .usersystem.UserModel userModel = 2;</code>
   */
  private void clearUserModel() {  userModel_ = null;
    bitField0_ = (bitField0_ & ~0x00000002);
  }

  public static final int TOKEN_FIELD_NUMBER = 3;
  private java.lang.String token_;
  /**
   * <code>optional string token = 3;</code>
   */
  @java.lang.Override
  public boolean hasToken() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string token = 3;</code>
   */
  @java.lang.Override
  public java.lang.String getToken() {
    return token_;
  }
  /**
   * <code>optional string token = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTokenBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(token_);
  }
  /**
   * <code>optional string token = 3;</code>
   */
  private void setToken(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
    token_ = value;
  }
  /**
   * <code>optional string token = 3;</code>
   */
  private void clearToken() {
    bitField0_ = (bitField0_ & ~0x00000004);
    token_ = getDefaultInstance().getToken();
  }
  /**
   * <code>optional string token = 3;</code>
   */
  private void setTokenBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
    token_ = value.toStringUtf8();
  }

  public static com.wanghong.grpc.usersystem.proto.LoginResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.wanghong.grpc.usersystem.proto.LoginResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.wanghong.grpc.usersystem.proto.LoginResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.wanghong.grpc.usersystem.proto.LoginResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.wanghong.grpc.usersystem.proto.LoginResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.wanghong.grpc.usersystem.proto.LoginResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.wanghong.grpc.usersystem.proto.LoginResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.wanghong.grpc.usersystem.proto.LoginResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.wanghong.grpc.usersystem.proto.LoginResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.wanghong.grpc.usersystem.proto.LoginResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.wanghong.grpc.usersystem.proto.LoginResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.wanghong.grpc.usersystem.proto.LoginResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.wanghong.grpc.usersystem.proto.LoginResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code usersystem.LoginResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.wanghong.grpc.usersystem.proto.LoginResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:usersystem.LoginResponse)
      com.wanghong.grpc.usersystem.proto.LoginResponseOrBuilder {
    // Construct using com.wanghong.grpc.usersystem.proto.LoginResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>required .usersystem.CommonResponse response = 1;</code>
     */
    @java.lang.Override
    public boolean hasResponse() {
      return instance.hasResponse();
    }
    /**
     * <code>required .usersystem.CommonResponse response = 1;</code>
     */
    @java.lang.Override
    public com.wanghong.grpc.usersystem.proto.CommonResponse getResponse() {
      return instance.getResponse();
    }
    /**
     * <code>required .usersystem.CommonResponse response = 1;</code>
     */
    public Builder setResponse(com.wanghong.grpc.usersystem.proto.CommonResponse value) {
      copyOnWrite();
      instance.setResponse(value);
      return this;
      }
    /**
     * <code>required .usersystem.CommonResponse response = 1;</code>
     */
    public Builder setResponse(
        com.wanghong.grpc.usersystem.proto.CommonResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setResponse(builderForValue);
      return this;
    }
    /**
     * <code>required .usersystem.CommonResponse response = 1;</code>
     */
    public Builder mergeResponse(com.wanghong.grpc.usersystem.proto.CommonResponse value) {
      copyOnWrite();
      instance.mergeResponse(value);
      return this;
    }
    /**
     * <code>required .usersystem.CommonResponse response = 1;</code>
     */
    public Builder clearResponse() {  copyOnWrite();
      instance.clearResponse();
      return this;
    }

    /**
     * <code>optional .usersystem.UserModel userModel = 2;</code>
     */
    @java.lang.Override
    public boolean hasUserModel() {
      return instance.hasUserModel();
    }
    /**
     * <code>optional .usersystem.UserModel userModel = 2;</code>
     */
    @java.lang.Override
    public com.wanghong.grpc.usersystem.proto.UserModel getUserModel() {
      return instance.getUserModel();
    }
    /**
     * <code>optional .usersystem.UserModel userModel = 2;</code>
     */
    public Builder setUserModel(com.wanghong.grpc.usersystem.proto.UserModel value) {
      copyOnWrite();
      instance.setUserModel(value);
      return this;
      }
    /**
     * <code>optional .usersystem.UserModel userModel = 2;</code>
     */
    public Builder setUserModel(
        com.wanghong.grpc.usersystem.proto.UserModel.Builder builderForValue) {
      copyOnWrite();
      instance.setUserModel(builderForValue);
      return this;
    }
    /**
     * <code>optional .usersystem.UserModel userModel = 2;</code>
     */
    public Builder mergeUserModel(com.wanghong.grpc.usersystem.proto.UserModel value) {
      copyOnWrite();
      instance.mergeUserModel(value);
      return this;
    }
    /**
     * <code>optional .usersystem.UserModel userModel = 2;</code>
     */
    public Builder clearUserModel() {  copyOnWrite();
      instance.clearUserModel();
      return this;
    }

    /**
     * <code>optional string token = 3;</code>
     */
    @java.lang.Override
    public boolean hasToken() {
      return instance.hasToken();
    }
    /**
     * <code>optional string token = 3;</code>
     */
    @java.lang.Override
    public java.lang.String getToken() {
      return instance.getToken();
    }
    /**
     * <code>optional string token = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTokenBytes() {
      return instance.getTokenBytes();
    }
    /**
     * <code>optional string token = 3;</code>
     */
    public Builder setToken(
        java.lang.String value) {
      copyOnWrite();
      instance.setToken(value);
      return this;
    }
    /**
     * <code>optional string token = 3;</code>
     */
    public Builder clearToken() {
      copyOnWrite();
      instance.clearToken();
      return this;
    }
    /**
     * <code>optional string token = 3;</code>
     */
    public Builder setTokenBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTokenBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:usersystem.LoginResponse)
  }
  private byte memoizedIsInitialized = 2;
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.wanghong.grpc.usersystem.proto.LoginResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "response_",
            "userModel_",
            "token_",
          };
          java.lang.String info =
              "\u0001\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0002\u0001\u0509\u0000\u0002" +
              "\u0409\u0001\u0003\b\u0002";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.wanghong.grpc.usersystem.proto.LoginResponse> parser = PARSER;
        if (parser == null) {
          synchronized (com.wanghong.grpc.usersystem.proto.LoginResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return memoizedIsInitialized;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:usersystem.LoginResponse)
  private static final com.wanghong.grpc.usersystem.proto.LoginResponse DEFAULT_INSTANCE;
  static {
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = new LoginResponse();
  }

  static {
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      LoginResponse.class, DEFAULT_INSTANCE);
  }
  public static com.wanghong.grpc.usersystem.proto.LoginResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<LoginResponse> PARSER;

  public static com.google.protobuf.Parser<LoginResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

