// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usersystem.proto

package com.wanghong.grpc.usersystem.proto;

/**
 * Protobuf type {@code usersystem.LogoutRequest}
 */
public  final class LogoutRequest extends
    com.google.protobuf.GeneratedMessageLite<
        LogoutRequest, LogoutRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:usersystem.LogoutRequest)
    LogoutRequestOrBuilder {
  private LogoutRequest() {
    username_ = "";
    token_ = "";
  }
  private int bitField0_;
  public static final int USERNAME_FIELD_NUMBER = 1;
  private java.lang.String username_;
  /**
   * <code>required string username = 1;</code>
   */
  @java.lang.Override
  public boolean hasUsername() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required string username = 1;</code>
   */
  @java.lang.Override
  public java.lang.String getUsername() {
    return username_;
  }
  /**
   * <code>required string username = 1;</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(username_);
  }
  /**
   * <code>required string username = 1;</code>
   */
  private void setUsername(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
    username_ = value;
  }
  /**
   * <code>required string username = 1;</code>
   */
  private void clearUsername() {
    bitField0_ = (bitField0_ & ~0x00000001);
    username_ = getDefaultInstance().getUsername();
  }
  /**
   * <code>required string username = 1;</code>
   */
  private void setUsernameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
    username_ = value.toStringUtf8();
  }

  public static final int TOKEN_FIELD_NUMBER = 2;
  private java.lang.String token_;
  /**
   * <code>required string token = 2;</code>
   */
  @java.lang.Override
  public boolean hasToken() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required string token = 2;</code>
   */
  @java.lang.Override
  public java.lang.String getToken() {
    return token_;
  }
  /**
   * <code>required string token = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTokenBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(token_);
  }
  /**
   * <code>required string token = 2;</code>
   */
  private void setToken(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
    token_ = value;
  }
  /**
   * <code>required string token = 2;</code>
   */
  private void clearToken() {
    bitField0_ = (bitField0_ & ~0x00000002);
    token_ = getDefaultInstance().getToken();
  }
  /**
   * <code>required string token = 2;</code>
   */
  private void setTokenBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
    token_ = value.toStringUtf8();
  }

  public static com.wanghong.grpc.usersystem.proto.LogoutRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.wanghong.grpc.usersystem.proto.LogoutRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.wanghong.grpc.usersystem.proto.LogoutRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.wanghong.grpc.usersystem.proto.LogoutRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.wanghong.grpc.usersystem.proto.LogoutRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.wanghong.grpc.usersystem.proto.LogoutRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.wanghong.grpc.usersystem.proto.LogoutRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.wanghong.grpc.usersystem.proto.LogoutRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.wanghong.grpc.usersystem.proto.LogoutRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.wanghong.grpc.usersystem.proto.LogoutRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.wanghong.grpc.usersystem.proto.LogoutRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.wanghong.grpc.usersystem.proto.LogoutRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.wanghong.grpc.usersystem.proto.LogoutRequest prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code usersystem.LogoutRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.wanghong.grpc.usersystem.proto.LogoutRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:usersystem.LogoutRequest)
      com.wanghong.grpc.usersystem.proto.LogoutRequestOrBuilder {
    // Construct using com.wanghong.grpc.usersystem.proto.LogoutRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>required string username = 1;</code>
     */
    @java.lang.Override
    public boolean hasUsername() {
      return instance.hasUsername();
    }
    /**
     * <code>required string username = 1;</code>
     */
    @java.lang.Override
    public java.lang.String getUsername() {
      return instance.getUsername();
    }
    /**
     * <code>required string username = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      return instance.getUsernameBytes();
    }
    /**
     * <code>required string username = 1;</code>
     */
    public Builder setUsername(
        java.lang.String value) {
      copyOnWrite();
      instance.setUsername(value);
      return this;
    }
    /**
     * <code>required string username = 1;</code>
     */
    public Builder clearUsername() {
      copyOnWrite();
      instance.clearUsername();
      return this;
    }
    /**
     * <code>required string username = 1;</code>
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUsernameBytes(value);
      return this;
    }

    /**
     * <code>required string token = 2;</code>
     */
    @java.lang.Override
    public boolean hasToken() {
      return instance.hasToken();
    }
    /**
     * <code>required string token = 2;</code>
     */
    @java.lang.Override
    public java.lang.String getToken() {
      return instance.getToken();
    }
    /**
     * <code>required string token = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTokenBytes() {
      return instance.getTokenBytes();
    }
    /**
     * <code>required string token = 2;</code>
     */
    public Builder setToken(
        java.lang.String value) {
      copyOnWrite();
      instance.setToken(value);
      return this;
    }
    /**
     * <code>required string token = 2;</code>
     */
    public Builder clearToken() {
      copyOnWrite();
      instance.clearToken();
      return this;
    }
    /**
     * <code>required string token = 2;</code>
     */
    public Builder setTokenBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTokenBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:usersystem.LogoutRequest)
  }
  private byte memoizedIsInitialized = 2;
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.wanghong.grpc.usersystem.proto.LogoutRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "username_",
            "token_",
          };
          java.lang.String info =
              "\u0001\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0002\u0001\u0508\u0000\u0002" +
              "\u0508\u0001";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.wanghong.grpc.usersystem.proto.LogoutRequest> parser = PARSER;
        if (parser == null) {
          synchronized (com.wanghong.grpc.usersystem.proto.LogoutRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return memoizedIsInitialized;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:usersystem.LogoutRequest)
  private static final com.wanghong.grpc.usersystem.proto.LogoutRequest DEFAULT_INSTANCE;
  static {
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = new LogoutRequest();
  }

  static {
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      LogoutRequest.class, DEFAULT_INSTANCE);
  }
  public static com.wanghong.grpc.usersystem.proto.LogoutRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<LogoutRequest> PARSER;

  public static com.google.protobuf.Parser<LogoutRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

