// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usersystem.proto

package com.wanghong.grpc.usersystem.proto;

public interface LogoutRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:usersystem.LogoutRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>required string username = 1;</code>
   */
  boolean hasUsername();
  /**
   * <code>required string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>required string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
