// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usersystem.proto

package com.wanghong.grpc.usersystem.proto;

/**
 * Protobuf enum {@code usersystem.Platform}
 */
public enum Platform
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>Type_Desktop = 0;</code>
   */
  Type_Desktop(0),
  /**
   * <pre>
   * do not use ANDROID conflict with android build system
   * </pre>
   *
   * <code>Type_Android = 1;</code>
   */
  Type_Android(1),
  /**
   * <code>Type_iOS = 2;</code>
   */
  Type_iOS(2),
  ;

  /**
   * <code>Type_Desktop = 0;</code>
   */
  public static final int Type_Desktop_VALUE = 0;
  /**
   * <pre>
   * do not use ANDROID conflict with android build system
   * </pre>
   *
   * <code>Type_Android = 1;</code>
   */
  public static final int Type_Android_VALUE = 1;
  /**
   * <code>Type_iOS = 2;</code>
   */
  public static final int Type_iOS_VALUE = 2;


  @java.lang.Override
  public final int getNumber() {
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Platform valueOf(int value) {
    return forNumber(value);
  }

  public static Platform forNumber(int value) {
    switch (value) {
      case 0: return Type_Desktop;
      case 1: return Type_Android;
      case 2: return Type_iOS;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Platform>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Platform> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Platform>() {
          @java.lang.Override
          public Platform findValueByNumber(int number) {
            return Platform.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return PlatformVerifier.INSTANCE;
  }

  private static final class PlatformVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new PlatformVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return Platform.forNumber(number) != null;
          }
        };

  private final int value;

  private Platform(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:usersystem.Platform)
}

