// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usersystem.proto

package com.wanghong.grpc.usersystem.proto;

public interface RegisterResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:usersystem.RegisterResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>required .usersystem.CommonResponse response = 1;</code>
   */
  boolean hasResponse();
  /**
   * <code>required .usersystem.CommonResponse response = 1;</code>
   */
  com.wanghong.grpc.usersystem.proto.CommonResponse getResponse();

  /**
   * <code>optional .usersystem.UserModel userModel = 2;</code>
   */
  boolean hasUserModel();
  /**
   * <code>optional .usersystem.UserModel userModel = 2;</code>
   */
  com.wanghong.grpc.usersystem.proto.UserModel getUserModel();

  /**
   * <code>optional string token = 3;</code>
   */
  boolean hasToken();
  /**
   * <code>optional string token = 3;</code>
   */
  java.lang.String getToken();
  /**
   * <code>optional string token = 3;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
