// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usersystem.proto

package com.wanghong.grpc.usersystem.proto;

/**
 * Protobuf enum {@code usersystem.ResponseCode}
 */
public enum ResponseCode
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>OK = 0;</code>
   */
  OK(0),
  /**
   * <code>ERROR_REGISTER_USERNAME_HAS_BEEN_TAKEN = 1;</code>
   */
  ERROR_REGISTER_USERNAME_HAS_BEEN_TAKEN(1),
  /**
   * <code>ERROR_REGISTER_EMPTY_USERNAME_PASSWORD = 2;</code>
   */
  ERROR_REGISTER_EMPTY_USERNAME_PASSWORD(2),
  /**
   * <pre>
   * no such user, register required
   * </pre>
   *
   * <code>ERROR_LOGIN_WRONG_USERNAME = 3;</code>
   */
  ERROR_LOGIN_WRONG_USERNAME(3),
  /**
   * <pre>
   * no password, try again
   * </pre>
   *
   * <code>ERROR_LOGIN_WRONG_PASSWORD = 4;</code>
   */
  ERROR_LOGIN_WRONG_PASSWORD(4),
  /**
   * <code>ERROR_LOGIN_STATUS_INVALID = 5;</code>
   */
  ERROR_LOGIN_STATUS_INVALID(5),
  /**
   * <code>ERROR_ANDROID_JNI_CALL = 6;</code>
   */
  ERROR_ANDROID_JNI_CALL(6),
  /**
   * <code>ERROR_GRPC_ERROR = 7;</code>
   */
  ERROR_GRPC_ERROR(7),
  /**
   * <code>ERROR_INVALID_USERNAME = 8;</code>
   */
  ERROR_INVALID_USERNAME(8),
  /**
   * <code>ERROR_UNKNOWN = 9;</code>
   */
  ERROR_UNKNOWN(9),
  ;

  /**
   * <code>OK = 0;</code>
   */
  public static final int OK_VALUE = 0;
  /**
   * <code>ERROR_REGISTER_USERNAME_HAS_BEEN_TAKEN = 1;</code>
   */
  public static final int ERROR_REGISTER_USERNAME_HAS_BEEN_TAKEN_VALUE = 1;
  /**
   * <code>ERROR_REGISTER_EMPTY_USERNAME_PASSWORD = 2;</code>
   */
  public static final int ERROR_REGISTER_EMPTY_USERNAME_PASSWORD_VALUE = 2;
  /**
   * <pre>
   * no such user, register required
   * </pre>
   *
   * <code>ERROR_LOGIN_WRONG_USERNAME = 3;</code>
   */
  public static final int ERROR_LOGIN_WRONG_USERNAME_VALUE = 3;
  /**
   * <pre>
   * no password, try again
   * </pre>
   *
   * <code>ERROR_LOGIN_WRONG_PASSWORD = 4;</code>
   */
  public static final int ERROR_LOGIN_WRONG_PASSWORD_VALUE = 4;
  /**
   * <code>ERROR_LOGIN_STATUS_INVALID = 5;</code>
   */
  public static final int ERROR_LOGIN_STATUS_INVALID_VALUE = 5;
  /**
   * <code>ERROR_ANDROID_JNI_CALL = 6;</code>
   */
  public static final int ERROR_ANDROID_JNI_CALL_VALUE = 6;
  /**
   * <code>ERROR_GRPC_ERROR = 7;</code>
   */
  public static final int ERROR_GRPC_ERROR_VALUE = 7;
  /**
   * <code>ERROR_INVALID_USERNAME = 8;</code>
   */
  public static final int ERROR_INVALID_USERNAME_VALUE = 8;
  /**
   * <code>ERROR_UNKNOWN = 9;</code>
   */
  public static final int ERROR_UNKNOWN_VALUE = 9;


  @java.lang.Override
  public final int getNumber() {
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ResponseCode valueOf(int value) {
    return forNumber(value);
  }

  public static ResponseCode forNumber(int value) {
    switch (value) {
      case 0: return OK;
      case 1: return ERROR_REGISTER_USERNAME_HAS_BEEN_TAKEN;
      case 2: return ERROR_REGISTER_EMPTY_USERNAME_PASSWORD;
      case 3: return ERROR_LOGIN_WRONG_USERNAME;
      case 4: return ERROR_LOGIN_WRONG_PASSWORD;
      case 5: return ERROR_LOGIN_STATUS_INVALID;
      case 6: return ERROR_ANDROID_JNI_CALL;
      case 7: return ERROR_GRPC_ERROR;
      case 8: return ERROR_INVALID_USERNAME;
      case 9: return ERROR_UNKNOWN;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ResponseCode>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ResponseCode> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ResponseCode>() {
          @java.lang.Override
          public ResponseCode findValueByNumber(int number) {
            return ResponseCode.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return ResponseCodeVerifier.INSTANCE;
  }

  private static final class ResponseCodeVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new ResponseCodeVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return ResponseCode.forNumber(number) != null;
          }
        };

  private final int value;

  private ResponseCode(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:usersystem.ResponseCode)
}

