// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usersystem.proto

package com.wanghong.grpc.usersystem.proto;

/**
 * Protobuf type {@code usersystem.UserModel}
 */
public  final class UserModel extends
    com.google.protobuf.GeneratedMessageLite<
        UserModel, UserModel.Builder> implements
    // @@protoc_insertion_point(message_implements:usersystem.UserModel)
    UserModelOrBuilder {
  private UserModel() {
    id_ = "";
    username_ = "";
    password_ = "";
    phoneNumber_ = "";
  }
  /**
   * Protobuf enum {@code usersystem.UserModel.UserGender}
   */
  public enum UserGender
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>MALE = 0;</code>
     */
    MALE(0),
    /**
     * <code>FEMALE = 1;</code>
     */
    FEMALE(1),
    /**
     * <code>NEUTER = 2;</code>
     */
    NEUTER(2),
    ;

    /**
     * <code>MALE = 0;</code>
     */
    public static final int MALE_VALUE = 0;
    /**
     * <code>FEMALE = 1;</code>
     */
    public static final int FEMALE_VALUE = 1;
    /**
     * <code>NEUTER = 2;</code>
     */
    public static final int NEUTER_VALUE = 2;


    @java.lang.Override
    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static UserGender valueOf(int value) {
      return forNumber(value);
    }

    public static UserGender forNumber(int value) {
      switch (value) {
        case 0: return MALE;
        case 1: return FEMALE;
        case 2: return NEUTER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<UserGender>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        UserGender> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<UserGender>() {
            @java.lang.Override
            public UserGender findValueByNumber(int number) {
              return UserGender.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return UserGenderVerifier.INSTANCE;
    }

    private static final class UserGenderVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new UserGenderVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return UserGender.forNumber(number) != null;
            }
          };

    private final int value;

    private UserGender(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:usersystem.UserModel.UserGender)
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private java.lang.String id_;
  /**
   * <code>required string id = 1;</code>
   */
  @java.lang.Override
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required string id = 1;</code>
   */
  @java.lang.Override
  public java.lang.String getId() {
    return id_;
  }
  /**
   * <code>required string id = 1;</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(id_);
  }
  /**
   * <code>required string id = 1;</code>
   */
  private void setId(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
    id_ = value;
  }
  /**
   * <code>required string id = 1;</code>
   */
  private void clearId() {
    bitField0_ = (bitField0_ & ~0x00000001);
    id_ = getDefaultInstance().getId();
  }
  /**
   * <code>required string id = 1;</code>
   */
  private void setIdBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
    id_ = value.toStringUtf8();
  }

  public static final int USERNAME_FIELD_NUMBER = 2;
  private java.lang.String username_;
  /**
   * <code>required string username = 2;</code>
   */
  @java.lang.Override
  public boolean hasUsername() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required string username = 2;</code>
   */
  @java.lang.Override
  public java.lang.String getUsername() {
    return username_;
  }
  /**
   * <code>required string username = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(username_);
  }
  /**
   * <code>required string username = 2;</code>
   */
  private void setUsername(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
    username_ = value;
  }
  /**
   * <code>required string username = 2;</code>
   */
  private void clearUsername() {
    bitField0_ = (bitField0_ & ~0x00000002);
    username_ = getDefaultInstance().getUsername();
  }
  /**
   * <code>required string username = 2;</code>
   */
  private void setUsernameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
    username_ = value.toStringUtf8();
  }

  public static final int PASSWORD_FIELD_NUMBER = 3;
  private java.lang.String password_;
  /**
   * <code>optional string password = 3;</code>
   */
  @java.lang.Override
  public boolean hasPassword() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string password = 3;</code>
   */
  @java.lang.Override
  public java.lang.String getPassword() {
    return password_;
  }
  /**
   * <code>optional string password = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPasswordBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(password_);
  }
  /**
   * <code>optional string password = 3;</code>
   */
  private void setPassword(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
    password_ = value;
  }
  /**
   * <code>optional string password = 3;</code>
   */
  private void clearPassword() {
    bitField0_ = (bitField0_ & ~0x00000004);
    password_ = getDefaultInstance().getPassword();
  }
  /**
   * <code>optional string password = 3;</code>
   */
  private void setPasswordBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
    password_ = value.toStringUtf8();
  }

  public static final int AGE_FIELD_NUMBER = 4;
  private int age_;
  /**
   * <code>optional int32 age = 4;</code>
   */
  @java.lang.Override
  public boolean hasAge() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional int32 age = 4;</code>
   */
  @java.lang.Override
  public int getAge() {
    return age_;
  }
  /**
   * <code>optional int32 age = 4;</code>
   */
  private void setAge(int value) {
    bitField0_ |= 0x00000008;
    age_ = value;
  }
  /**
   * <code>optional int32 age = 4;</code>
   */
  private void clearAge() {
    bitField0_ = (bitField0_ & ~0x00000008);
    age_ = 0;
  }

  public static final int GENDER_FIELD_NUMBER = 5;
  private int gender_;
  /**
   * <code>optional .usersystem.UserModel.UserGender gender = 5;</code>
   */
  @java.lang.Override
  public boolean hasGender() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional .usersystem.UserModel.UserGender gender = 5;</code>
   */
  @java.lang.Override
  public com.wanghong.grpc.usersystem.proto.UserModel.UserGender getGender() {
    com.wanghong.grpc.usersystem.proto.UserModel.UserGender result = com.wanghong.grpc.usersystem.proto.UserModel.UserGender.forNumber(gender_);
    return result == null ? com.wanghong.grpc.usersystem.proto.UserModel.UserGender.MALE : result;
  }
  /**
   * <code>optional .usersystem.UserModel.UserGender gender = 5;</code>
   */
  private void setGender(com.wanghong.grpc.usersystem.proto.UserModel.UserGender value) {
    if (value == null) {
      throw new NullPointerException();
    }
    bitField0_ |= 0x00000010;
    gender_ = value.getNumber();
  }
  /**
   * <code>optional .usersystem.UserModel.UserGender gender = 5;</code>
   */
  private void clearGender() {
    bitField0_ = (bitField0_ & ~0x00000010);
    gender_ = 0;
  }

  public static final int PHONE_NUMBER_FIELD_NUMBER = 6;
  private java.lang.String phoneNumber_;
  /**
   * <code>optional string phone_number = 6;</code>
   */
  @java.lang.Override
  public boolean hasPhoneNumber() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional string phone_number = 6;</code>
   */
  @java.lang.Override
  public java.lang.String getPhoneNumber() {
    return phoneNumber_;
  }
  /**
   * <code>optional string phone_number = 6;</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPhoneNumberBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(phoneNumber_);
  }
  /**
   * <code>optional string phone_number = 6;</code>
   */
  private void setPhoneNumber(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
    phoneNumber_ = value;
  }
  /**
   * <code>optional string phone_number = 6;</code>
   */
  private void clearPhoneNumber() {
    bitField0_ = (bitField0_ & ~0x00000020);
    phoneNumber_ = getDefaultInstance().getPhoneNumber();
  }
  /**
   * <code>optional string phone_number = 6;</code>
   */
  private void setPhoneNumberBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
    phoneNumber_ = value.toStringUtf8();
  }

  public static final int GEO_FIELD_NUMBER = 7;
  private com.wanghong.grpc.usersystem.proto.Geo geo_;
  /**
   * <code>optional .usersystem.Geo geo = 7;</code>
   */
  @java.lang.Override
  public boolean hasGeo() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional .usersystem.Geo geo = 7;</code>
   */
  @java.lang.Override
  public com.wanghong.grpc.usersystem.proto.Geo getGeo() {
    return geo_ == null ? com.wanghong.grpc.usersystem.proto.Geo.getDefaultInstance() : geo_;
  }
  /**
   * <code>optional .usersystem.Geo geo = 7;</code>
   */
  private void setGeo(com.wanghong.grpc.usersystem.proto.Geo value) {
    if (value == null) {
      throw new NullPointerException();
    }
    geo_ = value;
    bitField0_ |= 0x00000040;
    }
  /**
   * <code>optional .usersystem.Geo geo = 7;</code>
   */
  private void setGeo(
      com.wanghong.grpc.usersystem.proto.Geo.Builder builderForValue) {
    geo_ = builderForValue.build();
    bitField0_ |= 0x00000040;
  }
  /**
   * <code>optional .usersystem.Geo geo = 7;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeGeo(com.wanghong.grpc.usersystem.proto.Geo value) {
    if (value == null) {
      throw new NullPointerException();
    }
    if (geo_ != null &&
        geo_ != com.wanghong.grpc.usersystem.proto.Geo.getDefaultInstance()) {
      geo_ =
        com.wanghong.grpc.usersystem.proto.Geo.newBuilder(geo_).mergeFrom(value).buildPartial();
    } else {
      geo_ = value;
    }
    bitField0_ |= 0x00000040;
  }
  /**
   * <code>optional .usersystem.Geo geo = 7;</code>
   */
  private void clearGeo() {  geo_ = null;
    bitField0_ = (bitField0_ & ~0x00000040);
  }

  public static final int CREATE_AT_MILLIS_FIELD_NUMBER = 8;
  private long createAtMillis_;
  /**
   * <code>optional uint64 create_at_millis = 8;</code>
   */
  @java.lang.Override
  public boolean hasCreateAtMillis() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <code>optional uint64 create_at_millis = 8;</code>
   */
  @java.lang.Override
  public long getCreateAtMillis() {
    return createAtMillis_;
  }
  /**
   * <code>optional uint64 create_at_millis = 8;</code>
   */
  private void setCreateAtMillis(long value) {
    bitField0_ |= 0x00000080;
    createAtMillis_ = value;
  }
  /**
   * <code>optional uint64 create_at_millis = 8;</code>
   */
  private void clearCreateAtMillis() {
    bitField0_ = (bitField0_ & ~0x00000080);
    createAtMillis_ = 0L;
  }

  public static final int UPDATE_AT_MILLIS_FIELD_NUMBER = 9;
  private long updateAtMillis_;
  /**
   * <code>optional uint64 update_at_millis = 9;</code>
   */
  @java.lang.Override
  public boolean hasUpdateAtMillis() {
    return ((bitField0_ & 0x00000100) != 0);
  }
  /**
   * <code>optional uint64 update_at_millis = 9;</code>
   */
  @java.lang.Override
  public long getUpdateAtMillis() {
    return updateAtMillis_;
  }
  /**
   * <code>optional uint64 update_at_millis = 9;</code>
   */
  private void setUpdateAtMillis(long value) {
    bitField0_ |= 0x00000100;
    updateAtMillis_ = value;
  }
  /**
   * <code>optional uint64 update_at_millis = 9;</code>
   */
  private void clearUpdateAtMillis() {
    bitField0_ = (bitField0_ & ~0x00000100);
    updateAtMillis_ = 0L;
  }

  public static com.wanghong.grpc.usersystem.proto.UserModel parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.wanghong.grpc.usersystem.proto.UserModel parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.wanghong.grpc.usersystem.proto.UserModel parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.wanghong.grpc.usersystem.proto.UserModel parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.wanghong.grpc.usersystem.proto.UserModel parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.wanghong.grpc.usersystem.proto.UserModel parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.wanghong.grpc.usersystem.proto.UserModel parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.wanghong.grpc.usersystem.proto.UserModel parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.wanghong.grpc.usersystem.proto.UserModel parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.wanghong.grpc.usersystem.proto.UserModel parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.wanghong.grpc.usersystem.proto.UserModel parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.wanghong.grpc.usersystem.proto.UserModel parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.wanghong.grpc.usersystem.proto.UserModel prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code usersystem.UserModel}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.wanghong.grpc.usersystem.proto.UserModel, Builder> implements
      // @@protoc_insertion_point(builder_implements:usersystem.UserModel)
      com.wanghong.grpc.usersystem.proto.UserModelOrBuilder {
    // Construct using com.wanghong.grpc.usersystem.proto.UserModel.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>required string id = 1;</code>
     */
    @java.lang.Override
    public boolean hasId() {
      return instance.hasId();
    }
    /**
     * <code>required string id = 1;</code>
     */
    @java.lang.Override
    public java.lang.String getId() {
      return instance.getId();
    }
    /**
     * <code>required string id = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      return instance.getIdBytes();
    }
    /**
     * <code>required string id = 1;</code>
     */
    public Builder setId(
        java.lang.String value) {
      copyOnWrite();
      instance.setId(value);
      return this;
    }
    /**
     * <code>required string id = 1;</code>
     */
    public Builder clearId() {
      copyOnWrite();
      instance.clearId();
      return this;
    }
    /**
     * <code>required string id = 1;</code>
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setIdBytes(value);
      return this;
    }

    /**
     * <code>required string username = 2;</code>
     */
    @java.lang.Override
    public boolean hasUsername() {
      return instance.hasUsername();
    }
    /**
     * <code>required string username = 2;</code>
     */
    @java.lang.Override
    public java.lang.String getUsername() {
      return instance.getUsername();
    }
    /**
     * <code>required string username = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      return instance.getUsernameBytes();
    }
    /**
     * <code>required string username = 2;</code>
     */
    public Builder setUsername(
        java.lang.String value) {
      copyOnWrite();
      instance.setUsername(value);
      return this;
    }
    /**
     * <code>required string username = 2;</code>
     */
    public Builder clearUsername() {
      copyOnWrite();
      instance.clearUsername();
      return this;
    }
    /**
     * <code>required string username = 2;</code>
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUsernameBytes(value);
      return this;
    }

    /**
     * <code>optional string password = 3;</code>
     */
    @java.lang.Override
    public boolean hasPassword() {
      return instance.hasPassword();
    }
    /**
     * <code>optional string password = 3;</code>
     */
    @java.lang.Override
    public java.lang.String getPassword() {
      return instance.getPassword();
    }
    /**
     * <code>optional string password = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      return instance.getPasswordBytes();
    }
    /**
     * <code>optional string password = 3;</code>
     */
    public Builder setPassword(
        java.lang.String value) {
      copyOnWrite();
      instance.setPassword(value);
      return this;
    }
    /**
     * <code>optional string password = 3;</code>
     */
    public Builder clearPassword() {
      copyOnWrite();
      instance.clearPassword();
      return this;
    }
    /**
     * <code>optional string password = 3;</code>
     */
    public Builder setPasswordBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPasswordBytes(value);
      return this;
    }

    /**
     * <code>optional int32 age = 4;</code>
     */
    @java.lang.Override
    public boolean hasAge() {
      return instance.hasAge();
    }
    /**
     * <code>optional int32 age = 4;</code>
     */
    @java.lang.Override
    public int getAge() {
      return instance.getAge();
    }
    /**
     * <code>optional int32 age = 4;</code>
     */
    public Builder setAge(int value) {
      copyOnWrite();
      instance.setAge(value);
      return this;
    }
    /**
     * <code>optional int32 age = 4;</code>
     */
    public Builder clearAge() {
      copyOnWrite();
      instance.clearAge();
      return this;
    }

    /**
     * <code>optional .usersystem.UserModel.UserGender gender = 5;</code>
     */
    @java.lang.Override
    public boolean hasGender() {
      return instance.hasGender();
    }
    /**
     * <code>optional .usersystem.UserModel.UserGender gender = 5;</code>
     */
    @java.lang.Override
    public com.wanghong.grpc.usersystem.proto.UserModel.UserGender getGender() {
      return instance.getGender();
    }
    /**
     * <code>optional .usersystem.UserModel.UserGender gender = 5;</code>
     */
    public Builder setGender(com.wanghong.grpc.usersystem.proto.UserModel.UserGender value) {
      copyOnWrite();
      instance.setGender(value);
      return this;
    }
    /**
     * <code>optional .usersystem.UserModel.UserGender gender = 5;</code>
     */
    public Builder clearGender() {
      copyOnWrite();
      instance.clearGender();
      return this;
    }

    /**
     * <code>optional string phone_number = 6;</code>
     */
    @java.lang.Override
    public boolean hasPhoneNumber() {
      return instance.hasPhoneNumber();
    }
    /**
     * <code>optional string phone_number = 6;</code>
     */
    @java.lang.Override
    public java.lang.String getPhoneNumber() {
      return instance.getPhoneNumber();
    }
    /**
     * <code>optional string phone_number = 6;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPhoneNumberBytes() {
      return instance.getPhoneNumberBytes();
    }
    /**
     * <code>optional string phone_number = 6;</code>
     */
    public Builder setPhoneNumber(
        java.lang.String value) {
      copyOnWrite();
      instance.setPhoneNumber(value);
      return this;
    }
    /**
     * <code>optional string phone_number = 6;</code>
     */
    public Builder clearPhoneNumber() {
      copyOnWrite();
      instance.clearPhoneNumber();
      return this;
    }
    /**
     * <code>optional string phone_number = 6;</code>
     */
    public Builder setPhoneNumberBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPhoneNumberBytes(value);
      return this;
    }

    /**
     * <code>optional .usersystem.Geo geo = 7;</code>
     */
    @java.lang.Override
    public boolean hasGeo() {
      return instance.hasGeo();
    }
    /**
     * <code>optional .usersystem.Geo geo = 7;</code>
     */
    @java.lang.Override
    public com.wanghong.grpc.usersystem.proto.Geo getGeo() {
      return instance.getGeo();
    }
    /**
     * <code>optional .usersystem.Geo geo = 7;</code>
     */
    public Builder setGeo(com.wanghong.grpc.usersystem.proto.Geo value) {
      copyOnWrite();
      instance.setGeo(value);
      return this;
      }
    /**
     * <code>optional .usersystem.Geo geo = 7;</code>
     */
    public Builder setGeo(
        com.wanghong.grpc.usersystem.proto.Geo.Builder builderForValue) {
      copyOnWrite();
      instance.setGeo(builderForValue);
      return this;
    }
    /**
     * <code>optional .usersystem.Geo geo = 7;</code>
     */
    public Builder mergeGeo(com.wanghong.grpc.usersystem.proto.Geo value) {
      copyOnWrite();
      instance.mergeGeo(value);
      return this;
    }
    /**
     * <code>optional .usersystem.Geo geo = 7;</code>
     */
    public Builder clearGeo() {  copyOnWrite();
      instance.clearGeo();
      return this;
    }

    /**
     * <code>optional uint64 create_at_millis = 8;</code>
     */
    @java.lang.Override
    public boolean hasCreateAtMillis() {
      return instance.hasCreateAtMillis();
    }
    /**
     * <code>optional uint64 create_at_millis = 8;</code>
     */
    @java.lang.Override
    public long getCreateAtMillis() {
      return instance.getCreateAtMillis();
    }
    /**
     * <code>optional uint64 create_at_millis = 8;</code>
     */
    public Builder setCreateAtMillis(long value) {
      copyOnWrite();
      instance.setCreateAtMillis(value);
      return this;
    }
    /**
     * <code>optional uint64 create_at_millis = 8;</code>
     */
    public Builder clearCreateAtMillis() {
      copyOnWrite();
      instance.clearCreateAtMillis();
      return this;
    }

    /**
     * <code>optional uint64 update_at_millis = 9;</code>
     */
    @java.lang.Override
    public boolean hasUpdateAtMillis() {
      return instance.hasUpdateAtMillis();
    }
    /**
     * <code>optional uint64 update_at_millis = 9;</code>
     */
    @java.lang.Override
    public long getUpdateAtMillis() {
      return instance.getUpdateAtMillis();
    }
    /**
     * <code>optional uint64 update_at_millis = 9;</code>
     */
    public Builder setUpdateAtMillis(long value) {
      copyOnWrite();
      instance.setUpdateAtMillis(value);
      return this;
    }
    /**
     * <code>optional uint64 update_at_millis = 9;</code>
     */
    public Builder clearUpdateAtMillis() {
      copyOnWrite();
      instance.clearUpdateAtMillis();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:usersystem.UserModel)
  }
  private byte memoizedIsInitialized = 2;
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.wanghong.grpc.usersystem.proto.UserModel();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "id_",
            "username_",
            "password_",
            "age_",
            "gender_",
            com.wanghong.grpc.usersystem.proto.UserModel.UserGender.internalGetVerifier(),
            "phoneNumber_",
            "geo_",
            "createAtMillis_",
            "updateAtMillis_",
          };
          java.lang.String info =
              "\u0001\t\u0000\u0001\u0001\t\t\u0000\u0000\u0003\u0001\u0508\u0000\u0002\u0508\u0001" +
              "\u0003\b\u0002\u0004\u0004\u0003\u0005\f\u0004\u0006\b\u0005\u0007\u0409\u0006\b" +
              "\u0003\u0007\t\u0003\b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.wanghong.grpc.usersystem.proto.UserModel> parser = PARSER;
        if (parser == null) {
          synchronized (com.wanghong.grpc.usersystem.proto.UserModel.class) {
            parser = PARSER;
            if (parser == null) {
              parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return memoizedIsInitialized;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:usersystem.UserModel)
  private static final com.wanghong.grpc.usersystem.proto.UserModel DEFAULT_INSTANCE;
  static {
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = new UserModel();
  }

  static {
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      UserModel.class, DEFAULT_INSTANCE);
  }
  public static com.wanghong.grpc.usersystem.proto.UserModel getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<UserModel> PARSER;

  public static com.google.protobuf.Parser<UserModel> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

