// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usersystem.proto

package com.wanghong.grpc.usersystem.proto;

public interface UserLoginHistoryModelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:usersystem.UserLoginHistoryModel)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>required string id = 1;</code>
   */
  boolean hasId();
  /**
   * <code>required string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>required string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>required string username = 2;</code>
   */
  boolean hasUsername();
  /**
   * <code>required string username = 2;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>required string username = 2;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>required string token = 3;</code>
   */
  boolean hasToken();
  /**
   * <code>required string token = 3;</code>
   */
  java.lang.String getToken();
  /**
   * <code>required string token = 3;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>required string device_id = 4;</code>
   */
  boolean hasDeviceId();
  /**
   * <code>required string device_id = 4;</code>
   */
  java.lang.String getDeviceId();
  /**
   * <code>required string device_id = 4;</code>
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <code>required .usersystem.Platform from_platform = 5;</code>
   */
  boolean hasFromPlatform();
  /**
   * <code>required .usersystem.Platform from_platform = 5;</code>
   */
  com.wanghong.grpc.usersystem.proto.Platform getFromPlatform();

  /**
   * <code>required bool is_valid = 6;</code>
   */
  boolean hasIsValid();
  /**
   * <code>required bool is_valid = 6;</code>
   */
  boolean getIsValid();

  /**
   * <code>optional uint64 create_at_millis = 7;</code>
   */
  boolean hasCreateAtMillis();
  /**
   * <code>optional uint64 create_at_millis = 7;</code>
   */
  long getCreateAtMillis();

  /**
   * <code>optional uint64 update_at_millis = 8;</code>
   */
  boolean hasUpdateAtMillis();
  /**
   * <code>optional uint64 update_at_millis = 8;</code>
   */
  long getUpdateAtMillis();

  /**
   * <code>optional uint64 expire_at_millis = 9;</code>
   */
  boolean hasExpireAtMillis();
  /**
   * <code>optional uint64 expire_at_millis = 9;</code>
   */
  long getExpireAtMillis();
}
