// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usersystem.proto

package com.wanghong.grpc.usersystem.proto;

/**
 * Protobuf type {@code usersystem.UserLoginHistoryModel}
 */
public  final class UserLoginHistoryModel extends
    com.google.protobuf.GeneratedMessageLite<
        UserLoginHistoryModel, UserLoginHistoryModel.Builder> implements
    // @@protoc_insertion_point(message_implements:usersystem.UserLoginHistoryModel)
    UserLoginHistoryModelOrBuilder {
  private UserLoginHistoryModel() {
    id_ = "";
    username_ = "";
    token_ = "";
    deviceId_ = "";
  }
  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private java.lang.String id_;
  /**
   * <code>required string id = 1;</code>
   */
  @java.lang.Override
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required string id = 1;</code>
   */
  @java.lang.Override
  public java.lang.String getId() {
    return id_;
  }
  /**
   * <code>required string id = 1;</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(id_);
  }
  /**
   * <code>required string id = 1;</code>
   */
  private void setId(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
    id_ = value;
  }
  /**
   * <code>required string id = 1;</code>
   */
  private void clearId() {
    bitField0_ = (bitField0_ & ~0x00000001);
    id_ = getDefaultInstance().getId();
  }
  /**
   * <code>required string id = 1;</code>
   */
  private void setIdBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
    id_ = value.toStringUtf8();
  }

  public static final int USERNAME_FIELD_NUMBER = 2;
  private java.lang.String username_;
  /**
   * <code>required string username = 2;</code>
   */
  @java.lang.Override
  public boolean hasUsername() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required string username = 2;</code>
   */
  @java.lang.Override
  public java.lang.String getUsername() {
    return username_;
  }
  /**
   * <code>required string username = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(username_);
  }
  /**
   * <code>required string username = 2;</code>
   */
  private void setUsername(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
    username_ = value;
  }
  /**
   * <code>required string username = 2;</code>
   */
  private void clearUsername() {
    bitField0_ = (bitField0_ & ~0x00000002);
    username_ = getDefaultInstance().getUsername();
  }
  /**
   * <code>required string username = 2;</code>
   */
  private void setUsernameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
    username_ = value.toStringUtf8();
  }

  public static final int TOKEN_FIELD_NUMBER = 3;
  private java.lang.String token_;
  /**
   * <code>required string token = 3;</code>
   */
  @java.lang.Override
  public boolean hasToken() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>required string token = 3;</code>
   */
  @java.lang.Override
  public java.lang.String getToken() {
    return token_;
  }
  /**
   * <code>required string token = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTokenBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(token_);
  }
  /**
   * <code>required string token = 3;</code>
   */
  private void setToken(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
    token_ = value;
  }
  /**
   * <code>required string token = 3;</code>
   */
  private void clearToken() {
    bitField0_ = (bitField0_ & ~0x00000004);
    token_ = getDefaultInstance().getToken();
  }
  /**
   * <code>required string token = 3;</code>
   */
  private void setTokenBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
    token_ = value.toStringUtf8();
  }

  public static final int DEVICE_ID_FIELD_NUMBER = 4;
  private java.lang.String deviceId_;
  /**
   * <code>required string device_id = 4;</code>
   */
  @java.lang.Override
  public boolean hasDeviceId() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>required string device_id = 4;</code>
   */
  @java.lang.Override
  public java.lang.String getDeviceId() {
    return deviceId_;
  }
  /**
   * <code>required string device_id = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeviceIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(deviceId_);
  }
  /**
   * <code>required string device_id = 4;</code>
   */
  private void setDeviceId(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
    deviceId_ = value;
  }
  /**
   * <code>required string device_id = 4;</code>
   */
  private void clearDeviceId() {
    bitField0_ = (bitField0_ & ~0x00000008);
    deviceId_ = getDefaultInstance().getDeviceId();
  }
  /**
   * <code>required string device_id = 4;</code>
   */
  private void setDeviceIdBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
    deviceId_ = value.toStringUtf8();
  }

  public static final int FROM_PLATFORM_FIELD_NUMBER = 5;
  private int fromPlatform_;
  /**
   * <code>required .usersystem.Platform from_platform = 5;</code>
   */
  @java.lang.Override
  public boolean hasFromPlatform() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>required .usersystem.Platform from_platform = 5;</code>
   */
  @java.lang.Override
  public com.wanghong.grpc.usersystem.proto.Platform getFromPlatform() {
    com.wanghong.grpc.usersystem.proto.Platform result = com.wanghong.grpc.usersystem.proto.Platform.forNumber(fromPlatform_);
    return result == null ? com.wanghong.grpc.usersystem.proto.Platform.Type_Desktop : result;
  }
  /**
   * <code>required .usersystem.Platform from_platform = 5;</code>
   */
  private void setFromPlatform(com.wanghong.grpc.usersystem.proto.Platform value) {
    if (value == null) {
      throw new NullPointerException();
    }
    bitField0_ |= 0x00000010;
    fromPlatform_ = value.getNumber();
  }
  /**
   * <code>required .usersystem.Platform from_platform = 5;</code>
   */
  private void clearFromPlatform() {
    bitField0_ = (bitField0_ & ~0x00000010);
    fromPlatform_ = 0;
  }

  public static final int IS_VALID_FIELD_NUMBER = 6;
  private boolean isValid_;
  /**
   * <code>required bool is_valid = 6;</code>
   */
  @java.lang.Override
  public boolean hasIsValid() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>required bool is_valid = 6;</code>
   */
  @java.lang.Override
  public boolean getIsValid() {
    return isValid_;
  }
  /**
   * <code>required bool is_valid = 6;</code>
   */
  private void setIsValid(boolean value) {
    bitField0_ |= 0x00000020;
    isValid_ = value;
  }
  /**
   * <code>required bool is_valid = 6;</code>
   */
  private void clearIsValid() {
    bitField0_ = (bitField0_ & ~0x00000020);
    isValid_ = false;
  }

  public static final int CREATE_AT_MILLIS_FIELD_NUMBER = 7;
  private long createAtMillis_;
  /**
   * <code>optional uint64 create_at_millis = 7;</code>
   */
  @java.lang.Override
  public boolean hasCreateAtMillis() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional uint64 create_at_millis = 7;</code>
   */
  @java.lang.Override
  public long getCreateAtMillis() {
    return createAtMillis_;
  }
  /**
   * <code>optional uint64 create_at_millis = 7;</code>
   */
  private void setCreateAtMillis(long value) {
    bitField0_ |= 0x00000040;
    createAtMillis_ = value;
  }
  /**
   * <code>optional uint64 create_at_millis = 7;</code>
   */
  private void clearCreateAtMillis() {
    bitField0_ = (bitField0_ & ~0x00000040);
    createAtMillis_ = 0L;
  }

  public static final int UPDATE_AT_MILLIS_FIELD_NUMBER = 8;
  private long updateAtMillis_;
  /**
   * <code>optional uint64 update_at_millis = 8;</code>
   */
  @java.lang.Override
  public boolean hasUpdateAtMillis() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <code>optional uint64 update_at_millis = 8;</code>
   */
  @java.lang.Override
  public long getUpdateAtMillis() {
    return updateAtMillis_;
  }
  /**
   * <code>optional uint64 update_at_millis = 8;</code>
   */
  private void setUpdateAtMillis(long value) {
    bitField0_ |= 0x00000080;
    updateAtMillis_ = value;
  }
  /**
   * <code>optional uint64 update_at_millis = 8;</code>
   */
  private void clearUpdateAtMillis() {
    bitField0_ = (bitField0_ & ~0x00000080);
    updateAtMillis_ = 0L;
  }

  public static final int EXPIRE_AT_MILLIS_FIELD_NUMBER = 9;
  private long expireAtMillis_;
  /**
   * <code>optional uint64 expire_at_millis = 9;</code>
   */
  @java.lang.Override
  public boolean hasExpireAtMillis() {
    return ((bitField0_ & 0x00000100) != 0);
  }
  /**
   * <code>optional uint64 expire_at_millis = 9;</code>
   */
  @java.lang.Override
  public long getExpireAtMillis() {
    return expireAtMillis_;
  }
  /**
   * <code>optional uint64 expire_at_millis = 9;</code>
   */
  private void setExpireAtMillis(long value) {
    bitField0_ |= 0x00000100;
    expireAtMillis_ = value;
  }
  /**
   * <code>optional uint64 expire_at_millis = 9;</code>
   */
  private void clearExpireAtMillis() {
    bitField0_ = (bitField0_ & ~0x00000100);
    expireAtMillis_ = 0L;
  }

  public static com.wanghong.grpc.usersystem.proto.UserLoginHistoryModel parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.wanghong.grpc.usersystem.proto.UserLoginHistoryModel parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.wanghong.grpc.usersystem.proto.UserLoginHistoryModel parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.wanghong.grpc.usersystem.proto.UserLoginHistoryModel parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.wanghong.grpc.usersystem.proto.UserLoginHistoryModel parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.wanghong.grpc.usersystem.proto.UserLoginHistoryModel parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.wanghong.grpc.usersystem.proto.UserLoginHistoryModel parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.wanghong.grpc.usersystem.proto.UserLoginHistoryModel parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.wanghong.grpc.usersystem.proto.UserLoginHistoryModel parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.wanghong.grpc.usersystem.proto.UserLoginHistoryModel parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.wanghong.grpc.usersystem.proto.UserLoginHistoryModel parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.wanghong.grpc.usersystem.proto.UserLoginHistoryModel parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.wanghong.grpc.usersystem.proto.UserLoginHistoryModel prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code usersystem.UserLoginHistoryModel}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.wanghong.grpc.usersystem.proto.UserLoginHistoryModel, Builder> implements
      // @@protoc_insertion_point(builder_implements:usersystem.UserLoginHistoryModel)
      com.wanghong.grpc.usersystem.proto.UserLoginHistoryModelOrBuilder {
    // Construct using com.wanghong.grpc.usersystem.proto.UserLoginHistoryModel.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>required string id = 1;</code>
     */
    @java.lang.Override
    public boolean hasId() {
      return instance.hasId();
    }
    /**
     * <code>required string id = 1;</code>
     */
    @java.lang.Override
    public java.lang.String getId() {
      return instance.getId();
    }
    /**
     * <code>required string id = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      return instance.getIdBytes();
    }
    /**
     * <code>required string id = 1;</code>
     */
    public Builder setId(
        java.lang.String value) {
      copyOnWrite();
      instance.setId(value);
      return this;
    }
    /**
     * <code>required string id = 1;</code>
     */
    public Builder clearId() {
      copyOnWrite();
      instance.clearId();
      return this;
    }
    /**
     * <code>required string id = 1;</code>
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setIdBytes(value);
      return this;
    }

    /**
     * <code>required string username = 2;</code>
     */
    @java.lang.Override
    public boolean hasUsername() {
      return instance.hasUsername();
    }
    /**
     * <code>required string username = 2;</code>
     */
    @java.lang.Override
    public java.lang.String getUsername() {
      return instance.getUsername();
    }
    /**
     * <code>required string username = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      return instance.getUsernameBytes();
    }
    /**
     * <code>required string username = 2;</code>
     */
    public Builder setUsername(
        java.lang.String value) {
      copyOnWrite();
      instance.setUsername(value);
      return this;
    }
    /**
     * <code>required string username = 2;</code>
     */
    public Builder clearUsername() {
      copyOnWrite();
      instance.clearUsername();
      return this;
    }
    /**
     * <code>required string username = 2;</code>
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUsernameBytes(value);
      return this;
    }

    /**
     * <code>required string token = 3;</code>
     */
    @java.lang.Override
    public boolean hasToken() {
      return instance.hasToken();
    }
    /**
     * <code>required string token = 3;</code>
     */
    @java.lang.Override
    public java.lang.String getToken() {
      return instance.getToken();
    }
    /**
     * <code>required string token = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTokenBytes() {
      return instance.getTokenBytes();
    }
    /**
     * <code>required string token = 3;</code>
     */
    public Builder setToken(
        java.lang.String value) {
      copyOnWrite();
      instance.setToken(value);
      return this;
    }
    /**
     * <code>required string token = 3;</code>
     */
    public Builder clearToken() {
      copyOnWrite();
      instance.clearToken();
      return this;
    }
    /**
     * <code>required string token = 3;</code>
     */
    public Builder setTokenBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTokenBytes(value);
      return this;
    }

    /**
     * <code>required string device_id = 4;</code>
     */
    @java.lang.Override
    public boolean hasDeviceId() {
      return instance.hasDeviceId();
    }
    /**
     * <code>required string device_id = 4;</code>
     */
    @java.lang.Override
    public java.lang.String getDeviceId() {
      return instance.getDeviceId();
    }
    /**
     * <code>required string device_id = 4;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      return instance.getDeviceIdBytes();
    }
    /**
     * <code>required string device_id = 4;</code>
     */
    public Builder setDeviceId(
        java.lang.String value) {
      copyOnWrite();
      instance.setDeviceId(value);
      return this;
    }
    /**
     * <code>required string device_id = 4;</code>
     */
    public Builder clearDeviceId() {
      copyOnWrite();
      instance.clearDeviceId();
      return this;
    }
    /**
     * <code>required string device_id = 4;</code>
     */
    public Builder setDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDeviceIdBytes(value);
      return this;
    }

    /**
     * <code>required .usersystem.Platform from_platform = 5;</code>
     */
    @java.lang.Override
    public boolean hasFromPlatform() {
      return instance.hasFromPlatform();
    }
    /**
     * <code>required .usersystem.Platform from_platform = 5;</code>
     */
    @java.lang.Override
    public com.wanghong.grpc.usersystem.proto.Platform getFromPlatform() {
      return instance.getFromPlatform();
    }
    /**
     * <code>required .usersystem.Platform from_platform = 5;</code>
     */
    public Builder setFromPlatform(com.wanghong.grpc.usersystem.proto.Platform value) {
      copyOnWrite();
      instance.setFromPlatform(value);
      return this;
    }
    /**
     * <code>required .usersystem.Platform from_platform = 5;</code>
     */
    public Builder clearFromPlatform() {
      copyOnWrite();
      instance.clearFromPlatform();
      return this;
    }

    /**
     * <code>required bool is_valid = 6;</code>
     */
    @java.lang.Override
    public boolean hasIsValid() {
      return instance.hasIsValid();
    }
    /**
     * <code>required bool is_valid = 6;</code>
     */
    @java.lang.Override
    public boolean getIsValid() {
      return instance.getIsValid();
    }
    /**
     * <code>required bool is_valid = 6;</code>
     */
    public Builder setIsValid(boolean value) {
      copyOnWrite();
      instance.setIsValid(value);
      return this;
    }
    /**
     * <code>required bool is_valid = 6;</code>
     */
    public Builder clearIsValid() {
      copyOnWrite();
      instance.clearIsValid();
      return this;
    }

    /**
     * <code>optional uint64 create_at_millis = 7;</code>
     */
    @java.lang.Override
    public boolean hasCreateAtMillis() {
      return instance.hasCreateAtMillis();
    }
    /**
     * <code>optional uint64 create_at_millis = 7;</code>
     */
    @java.lang.Override
    public long getCreateAtMillis() {
      return instance.getCreateAtMillis();
    }
    /**
     * <code>optional uint64 create_at_millis = 7;</code>
     */
    public Builder setCreateAtMillis(long value) {
      copyOnWrite();
      instance.setCreateAtMillis(value);
      return this;
    }
    /**
     * <code>optional uint64 create_at_millis = 7;</code>
     */
    public Builder clearCreateAtMillis() {
      copyOnWrite();
      instance.clearCreateAtMillis();
      return this;
    }

    /**
     * <code>optional uint64 update_at_millis = 8;</code>
     */
    @java.lang.Override
    public boolean hasUpdateAtMillis() {
      return instance.hasUpdateAtMillis();
    }
    /**
     * <code>optional uint64 update_at_millis = 8;</code>
     */
    @java.lang.Override
    public long getUpdateAtMillis() {
      return instance.getUpdateAtMillis();
    }
    /**
     * <code>optional uint64 update_at_millis = 8;</code>
     */
    public Builder setUpdateAtMillis(long value) {
      copyOnWrite();
      instance.setUpdateAtMillis(value);
      return this;
    }
    /**
     * <code>optional uint64 update_at_millis = 8;</code>
     */
    public Builder clearUpdateAtMillis() {
      copyOnWrite();
      instance.clearUpdateAtMillis();
      return this;
    }

    /**
     * <code>optional uint64 expire_at_millis = 9;</code>
     */
    @java.lang.Override
    public boolean hasExpireAtMillis() {
      return instance.hasExpireAtMillis();
    }
    /**
     * <code>optional uint64 expire_at_millis = 9;</code>
     */
    @java.lang.Override
    public long getExpireAtMillis() {
      return instance.getExpireAtMillis();
    }
    /**
     * <code>optional uint64 expire_at_millis = 9;</code>
     */
    public Builder setExpireAtMillis(long value) {
      copyOnWrite();
      instance.setExpireAtMillis(value);
      return this;
    }
    /**
     * <code>optional uint64 expire_at_millis = 9;</code>
     */
    public Builder clearExpireAtMillis() {
      copyOnWrite();
      instance.clearExpireAtMillis();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:usersystem.UserLoginHistoryModel)
  }
  private byte memoizedIsInitialized = 2;
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.wanghong.grpc.usersystem.proto.UserLoginHistoryModel();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "id_",
            "username_",
            "token_",
            "deviceId_",
            "fromPlatform_",
            com.wanghong.grpc.usersystem.proto.Platform.internalGetVerifier(),
            "isValid_",
            "createAtMillis_",
            "updateAtMillis_",
            "expireAtMillis_",
          };
          java.lang.String info =
              "\u0001\t\u0000\u0001\u0001\t\t\u0000\u0000\u0006\u0001\u0508\u0000\u0002\u0508\u0001" +
              "\u0003\u0508\u0002\u0004\u0508\u0003\u0005\u050c\u0004\u0006\u0507\u0005\u0007\u0003" +
              "\u0006\b\u0003\u0007\t\u0003\b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.wanghong.grpc.usersystem.proto.UserLoginHistoryModel> parser = PARSER;
        if (parser == null) {
          synchronized (com.wanghong.grpc.usersystem.proto.UserLoginHistoryModel.class) {
            parser = PARSER;
            if (parser == null) {
              parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return memoizedIsInitialized;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:usersystem.UserLoginHistoryModel)
  private static final com.wanghong.grpc.usersystem.proto.UserLoginHistoryModel DEFAULT_INSTANCE;
  static {
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = new UserLoginHistoryModel();
  }

  static {
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      UserLoginHistoryModel.class, DEFAULT_INSTANCE);
  }
  public static com.wanghong.grpc.usersystem.proto.UserLoginHistoryModel getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<UserLoginHistoryModel> PARSER;

  public static com.google.protobuf.Parser<UserLoginHistoryModel> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

