load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "common",
    srcs = glob(["*.cc"]),
    hdrs = glob(["*.h"]),
    visibility = ["//visibility:public"],
)

#exports_files(["usersystem.pb.cc", "usersystem.grpc.pb.cc", "usersystem.grpc.pb.h", "usersystem.pb.h"])
